linters:
  enable:
    - errcheck
    - staticcheck
    - gocyclo
    - dupl
    - gosec
    - gofmt
    - goimports
    - govet
    - revive

linters-settings:
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  gosec:
    excludes:
      - G104
